/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h3";
  listItem?: "bullet";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type NavChildLink = {
  _type: "navChildLink";
  label: string;
  href: string;
};

export type NavItem = {
  _type: "navItem";
  label: string;
  href: string;
  childSource?:
    "none" | "manual" | "docLocales" | "missionCountries" | "ministries";
  children?: Array<
    {
      _key: string;
    } & NavChildLink
  >;
};

export type SocialLink = {
  _type: "socialLink";
  name: "Facebook" | "X" | "YouTube" | "Instagram" | "LinkedIn";
  href: string;
  label: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  caption?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
};

export type Cta = {
  _type: "cta";
  label: string;
  href: string;
};

export type MissionCountry = {
  _id: string;
  _type: "missionCountry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  order: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  name: string;
  role: string;
  order: number;
};

export type Ministry = {
  _id: string;
  _type: "ministry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  body: string;
  icon: "church" | "handHeart" | "book" | "baby" | "globe" | "users";
  order: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug:
    "ministries" | "missions" | "history" | "contact" | "bulletins" | "sermons";
  eyebrow?: string;
  title: string;
  intro?: string;
  seo?: Seo;
  showPlaceholderBadge?: boolean;
  paragraphs?: Array<string>;
  milestones?: Array<{
    year: string;
    title: string;
    body: string;
    _key: string;
  }>;
  tabsLabel?: string;
  emptyText?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow?: string;
    title: string;
    body: string;
    primaryCta?: Cta;
    secondaryCta?: Cta;
  };
  mission?: {
    title: string;
    statement: string;
  };
  contactCta?: {
    title: string;
    subtitle?: string;
    cta?: Cta;
  };
  testimonials?: {
    title: string;
    subtitle?: string;
    showPlaceholderBadge?: boolean;
  };
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items: Array<
    {
      _key: string;
    } & NavItem
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orgName: string;
  shortName: string;
  legalFooterName: string;
  phone: string;
  phoneHref: string;
  email: string;
  emailHref: string;
  address: string;
  mapUrl: string;
  copyrightYear: number;
  serviceDay: string;
  serviceTime: string;
  serviceNote?: string;
  footerBlurb?: string;
  navCtaLabel?: string;
  defaultSeo?: Seo;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Sermon = {
  _id: string;
  _type: "sermon";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date: string;
  title: string;
  scripture?: string;
  locale: "en" | "es" | "fr";
  speaker?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  pdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type Bulletin = {
  _id: string;
  _type: "bulletin";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date: string;
  title: string;
  scripture?: string;
  locale: "en" | "es" | "fr";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  pdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | RichText
  | NavChildLink
  | NavItem
  | SocialLink
  | SanityImageAssetReference
  | ImageWithAlt
  | SanityImageCrop
  | SanityImageHotspot
  | Seo
  | Cta
  | MissionCountry
  | Testimonial
  | Ministry
  | Page
  | HomePage
  | Navigation
  | SiteSettings
  | SanityFileAssetReference
  | Sermon
  | Bulletin
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: lib/sanity/queries.ts
// Variable: BULLETINS_QUERY
// Query: *[_type == "bulletin" && locale == $locale] | order(date desc) [$start...$end] {    date,    title,    scripture,    "fileUrl": file.asset->url,    "pdfUrl": pdf.asset->url  }
export type BULLETINS_QUERY_RESULT = Array<{
  date: string;
  title: string;
  scripture: string | null;
  fileUrl: string | null;
  pdfUrl: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: SERMONS_QUERY
// Query: *[_type == "sermon" && locale == $locale] | order(date desc) [$start...$end] {    date,    title,    scripture,    speaker,    "fileUrl": file.asset->url,    "pdfUrl": pdf.asset->url  }
export type SERMONS_QUERY_RESULT = Array<{
  date: string;
  title: string;
  scripture: string | null;
  speaker: string | null;
  fileUrl: string | null;
  pdfUrl: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: BULLETINS_COUNT_QUERY
// Query: count(*[_type == "bulletin" && locale == $locale])
export type BULLETINS_COUNT_QUERY_RESULT = number;

// Source: lib/sanity/queries.ts
// Variable: SERMONS_COUNT_QUERY
// Query: count(*[_type == "sermon" && locale == $locale])
export type SERMONS_COUNT_QUERY_RESULT = number;

// Source: lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      _id: "siteSettings";
      _type: "bulletin";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      date: string;
      title: string;
      scripture?: string;
      locale: "en" | "es" | "fr";
      file?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      pdf?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
    }
  | {
      _id: "siteSettings";
      _type: "homePage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      hero?: {
        eyebrow?: string;
        title: string;
        body: string;
        primaryCta?: Cta;
        secondaryCta?: Cta;
      };
      mission?: {
        title: string;
        statement: string;
      };
      contactCta?: {
        title: string;
        subtitle?: string;
        cta?: Cta;
      };
      testimonials?: {
        title: string;
        subtitle?: string;
        showPlaceholderBadge?: boolean;
      };
    }
  | {
      _id: "siteSettings";
      _type: "ministry";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name: string;
      body: string;
      icon: "baby" | "book" | "church" | "globe" | "handHeart" | "users";
      order: number;
    }
  | {
      _id: "siteSettings";
      _type: "missionCountry";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name: string;
      order: number;
    }
  | {
      _id: "siteSettings";
      _type: "navigation";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      items: Array<
        {
          _key: string;
        } & NavItem
      >;
    }
  | {
      _id: "siteSettings";
      _type: "page";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      slug:
        | "bulletins"
        | "contact"
        | "history"
        | "ministries"
        | "missions"
        | "sermons";
      eyebrow?: string;
      title: string;
      intro?: string;
      seo?: Seo;
      showPlaceholderBadge?: boolean;
      paragraphs?: Array<string>;
      milestones?: Array<{
        year: string;
        title: string;
        body: string;
        _key: string;
      }>;
      tabsLabel?: string;
      emptyText?: string;
    }
  | {
      _id: "siteSettings";
      _type: "sanity.fileAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      source?: SanityAssetSourceData;
    }
  | {
      _id: "siteSettings";
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    }
  | {
      _id: "siteSettings";
      _type: "sermon";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      date: string;
      title: string;
      scripture?: string;
      locale: "en" | "es" | "fr";
      speaker?: string;
      file?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      pdf?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
    }
  | {
      _id: "siteSettings";
      _type: "siteSettings";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      orgName: string;
      shortName: string;
      legalFooterName: string;
      phone: string;
      phoneHref: string;
      email: string;
      emailHref: string;
      address: string;
      mapUrl: string;
      copyrightYear: number;
      serviceDay: string;
      serviceTime: string;
      serviceNote?: string;
      footerBlurb?: string;
      navCtaLabel?: string;
      defaultSeo?: Seo;
    }
  | {
      _id: "siteSettings";
      _type: "testimonial";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      quote: string;
      name: string;
      role: string;
      order: number;
    }
  | null;

// Source: lib/sanity/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_id == "navigation"][0]{    items[]{ label, href, children[]{ label, href } }  }
export type NAVIGATION_QUERY_RESULT =
  | {
      items: Array<{
        label: string;
        href: string;
        children: Array<{
          label: string;
          href: string;
        }> | null;
      }>;
    }
  | {
      items: null;
    }
  | null;

// Source: lib/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]
export type HOME_PAGE_QUERY_RESULT =
  | {
      _id: "homePage";
      _type: "bulletin";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      date: string;
      title: string;
      scripture?: string;
      locale: "en" | "es" | "fr";
      file?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      pdf?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
    }
  | {
      _id: "homePage";
      _type: "homePage";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      hero?: {
        eyebrow?: string;
        title: string;
        body: string;
        primaryCta?: Cta;
        secondaryCta?: Cta;
      };
      mission?: {
        title: string;
        statement: string;
      };
      contactCta?: {
        title: string;
        subtitle?: string;
        cta?: Cta;
      };
      testimonials?: {
        title: string;
        subtitle?: string;
        showPlaceholderBadge?: boolean;
      };
    }
  | {
      _id: "homePage";
      _type: "ministry";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name: string;
      body: string;
      icon: "baby" | "book" | "church" | "globe" | "handHeart" | "users";
      order: number;
    }
  | {
      _id: "homePage";
      _type: "missionCountry";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name: string;
      order: number;
    }
  | {
      _id: "homePage";
      _type: "navigation";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      items: Array<
        {
          _key: string;
        } & NavItem
      >;
    }
  | {
      _id: "homePage";
      _type: "page";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      slug:
        | "bulletins"
        | "contact"
        | "history"
        | "ministries"
        | "missions"
        | "sermons";
      eyebrow?: string;
      title: string;
      intro?: string;
      seo?: Seo;
      showPlaceholderBadge?: boolean;
      paragraphs?: Array<string>;
      milestones?: Array<{
        year: string;
        title: string;
        body: string;
        _key: string;
      }>;
      tabsLabel?: string;
      emptyText?: string;
    }
  | {
      _id: "homePage";
      _type: "sanity.fileAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      source?: SanityAssetSourceData;
    }
  | {
      _id: "homePage";
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    }
  | {
      _id: "homePage";
      _type: "sermon";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      date: string;
      title: string;
      scripture?: string;
      locale: "en" | "es" | "fr";
      speaker?: string;
      file?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      pdf?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
    }
  | {
      _id: "homePage";
      _type: "siteSettings";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      orgName: string;
      shortName: string;
      legalFooterName: string;
      phone: string;
      phoneHref: string;
      email: string;
      emailHref: string;
      address: string;
      mapUrl: string;
      copyrightYear: number;
      serviceDay: string;
      serviceTime: string;
      serviceNote?: string;
      footerBlurb?: string;
      navCtaLabel?: string;
      defaultSeo?: Seo;
    }
  | {
      _id: "homePage";
      _type: "testimonial";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      quote: string;
      name: string;
      role: string;
      order: number;
    }
  | null;

// Source: lib/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug == $slug][0]
export type PAGE_QUERY_RESULT = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug:
    "bulletins" | "contact" | "history" | "ministries" | "missions" | "sermons";
  eyebrow?: string;
  title: string;
  intro?: string;
  seo?: Seo;
  showPlaceholderBadge?: boolean;
  paragraphs?: Array<string>;
  milestones?: Array<{
    year: string;
    title: string;
    body: string;
    _key: string;
  }>;
  tabsLabel?: string;
  emptyText?: string;
} | null;

// Source: lib/sanity/queries.ts
// Variable: MINISTRIES_QUERY
// Query: *[_type == "ministry"] | order(order asc) { name, body, icon }
export type MINISTRIES_QUERY_RESULT = Array<{
  name: string;
  body: string;
  icon: "baby" | "book" | "church" | "globe" | "handHeart" | "users";
}>;

// Source: lib/sanity/queries.ts
// Variable: MISSION_COUNTRIES_QUERY
// Query: *[_type == "missionCountry"] | order(order asc) { name }
export type MISSION_COUNTRIES_QUERY_RESULT = Array<{
  name: string;
}>;

// Source: lib/sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(order asc) { quote, name, role }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  quote: string;
  name: string;
  role: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "bulletin" && locale == $locale] | order(date desc) [$start...$end] {\n    date,\n    title,\n    scripture,\n    "fileUrl": file.asset->url,\n    "pdfUrl": pdf.asset->url\n  }\n': BULLETINS_QUERY_RESULT;
    '\n  *[_type == "sermon" && locale == $locale] | order(date desc) [$start...$end] {\n    date,\n    title,\n    scripture,\n    speaker,\n    "fileUrl": file.asset->url,\n    "pdfUrl": pdf.asset->url\n  }\n': SERMONS_QUERY_RESULT;
    '\n  count(*[_type == "bulletin" && locale == $locale])\n': BULLETINS_COUNT_QUERY_RESULT;
    '\n  count(*[_type == "sermon" && locale == $locale])\n': SERMONS_COUNT_QUERY_RESULT;
    '*[_id == "siteSettings"][0]': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_id == "navigation"][0]{\n    items[]{ label, href, children[]{ label, href } }\n  }\n': NAVIGATION_QUERY_RESULT;
    '*[_id == "homePage"][0]': HOME_PAGE_QUERY_RESULT;
    '*[_type == "page" && slug == $slug][0]': PAGE_QUERY_RESULT;
    '\n  *[_type == "ministry"] | order(order asc) { name, body, icon }\n': MINISTRIES_QUERY_RESULT;
    '\n  *[_type == "missionCountry"] | order(order asc) { name }\n': MISSION_COUNTRIES_QUERY_RESULT;
    '\n  *[_type == "testimonial"] | order(order asc) { quote, name, role }\n': TESTIMONIALS_QUERY_RESULT;
  }
}
