/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h3";
  listItem?: "bullet";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type NavChildLink = {
  _type: "navChildLink";
  label: string;
  href: string;
};

export type NavItem = {
  _type: "navItem";
  label: string;
  href: string;
  childSource?:
    "none" | "manual" | "docLocales" | "missionCountries" | "ministries";
  children?: Array<
    {
      _key: string;
    } & NavChildLink
  >;
};

export type SocialLink = {
  _type: "socialLink";
  name: "Facebook" | "X" | "YouTube" | "Instagram" | "LinkedIn";
  href: string;
  label: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  caption?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
};

export type Cta = {
  _type: "cta";
  label: string;
  href: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Sermon = {
  _id: string;
  _type: "sermon";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date: string;
  title: string;
  scripture?: string;
  locale: "en" | "es" | "fr";
  speaker?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  pdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type Bulletin = {
  _id: string;
  _type: "bulletin";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date: string;
  title: string;
  scripture?: string;
  locale: "en" | "es" | "fr";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  pdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | RichText
  | NavChildLink
  | NavItem
  | SocialLink
  | SanityImageAssetReference
  | ImageWithAlt
  | SanityImageCrop
  | SanityImageHotspot
  | Seo
  | Cta
  | SanityFileAssetReference
  | Sermon
  | Bulletin
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: lib/sanity/queries.ts
// Variable: BULLETINS_QUERY
// Query: *[_type == "bulletin" && locale == $locale] | order(date desc) [$start...$end] {    date,    title,    scripture,    "fileUrl": file.asset->url,    "pdfUrl": pdf.asset->url  }
export type BULLETINS_QUERY_RESULT = Array<{
  date: string;
  title: string;
  scripture: string | null;
  fileUrl: string | null;
  pdfUrl: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: SERMONS_QUERY
// Query: *[_type == "sermon" && locale == $locale] | order(date desc) [$start...$end] {    date,    title,    scripture,    speaker,    "fileUrl": file.asset->url,    "pdfUrl": pdf.asset->url  }
export type SERMONS_QUERY_RESULT = Array<{
  date: string;
  title: string;
  scripture: string | null;
  speaker: string | null;
  fileUrl: string | null;
  pdfUrl: string | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: BULLETINS_COUNT_QUERY
// Query: count(*[_type == "bulletin" && locale == $locale])
export type BULLETINS_COUNT_QUERY_RESULT = number;

// Source: lib/sanity/queries.ts
// Variable: SERMONS_COUNT_QUERY
// Query: count(*[_type == "sermon" && locale == $locale])
export type SERMONS_COUNT_QUERY_RESULT = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "bulletin" && locale == $locale] | order(date desc) [$start...$end] {\n    date,\n    title,\n    scripture,\n    "fileUrl": file.asset->url,\n    "pdfUrl": pdf.asset->url\n  }\n': BULLETINS_QUERY_RESULT;
    '\n  *[_type == "sermon" && locale == $locale] | order(date desc) [$start...$end] {\n    date,\n    title,\n    scripture,\n    speaker,\n    "fileUrl": file.asset->url,\n    "pdfUrl": pdf.asset->url\n  }\n': SERMONS_QUERY_RESULT;
    '\n  count(*[_type == "bulletin" && locale == $locale])\n': BULLETINS_COUNT_QUERY_RESULT;
    '\n  count(*[_type == "sermon" && locale == $locale])\n': SERMONS_COUNT_QUERY_RESULT;
  }
}
